server:
  port: 8080
  servlet:
    context-path: /identity

test:
  name: "mysslife"

spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/bookteria_identity} # sau dấu : có nghĩa là nếu không có biến môi trường thì dùng biến mặc định được truyền vào
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:HT@09021011}
    # jdbc:mysql://localhost:3306/bookteria_identity

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer # đầu gửi sẽ là value-serializer -> đầu nhận sẽ là value-deserializer

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 3600 # seconds / 1 hour
  refreshable-duration: 36000 # seconds / 10 hours

app:
  services:
    profile: "http://localhost:8081/profile"